auctionmanageronline/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'manager.views.home.home', name='home'),
    url(r'^login/$', 'manager.views.home.login', name='login'),
    url(r'^logout/$', 'manager.views.home.logout', name='logout'),


    url('^attendee/add/$', 'manager.views.attendee.create', name='add_attendee'),
    url('^attendee/(\d+)$', 'manager.views.attendee.info', name='attendee_info'),
    url('^attendee/update/(\d+)$', 'manager.views.attendee.update', name='update_attendee'),
    url('^attendee/all$', 'manager.views.attendee.list', name='attendee_list'),
    url('^attendee/delete/(\d+)$', 'manager.views.attendee.delete', name='delete_attendee'),
    url('^past-attendees$', 'manager.views.attendee.past_attendees', name='past_attendees'),

    url('^item/add/$', 'manager.views.auction_item.create', name='add_item'),
    url('^item/(\d+)$', 'manager.views.auction_item.detail', name='item_detail'),
    url('^item/update/(\d+)$', 'manager.views.auction_item.update', name='update_item'),
    url('^item/all$', 'manager.views.auction_item.list', name='item_list'),
    url('^item/delete/(\d+)$', 'manager.views.auction_item.delete', name='delete_item'),
    url('^item/search/$', 'manager.views.auction_item.item_search', name='item_search'),
    url('^item/unsold/all$', 'manager.views.auction_item.unsold_item_list', name='unsold_items'),
    url('^past-items$', 'manager.views.auction_item.past_items', name='past_items'),

    url('^invoice/add/$', 'manager.views.invoice.create', name='add_invoice'),
    url('^invoice/(\d+)$', 'manager.views.invoice.detail', name='invoice_details'),
    url('^invoice/bidder$', 'manager.views.invoice.bidder_invoice_search', name='bidder_invoice'),
    url('^invoice/update/(\d+)$', 'manager.views.invoice.update', name='update_invoice'),
    url('^invoice/all$', 'manager.views.invoice.list', name='invoice_list'),
    url('^invoice/delete/(\d+)$', 'manager.views.invoice.delete', name='delete_invoice'),
    url('^invoice/unpaid/$', 'manager.views.invoice.unpaid_invoices', name='unpaid_invoices'),

    url('^invoice/merge/$', 'manager.views.invoice.merge_invoices', name='merge_invoices'),
    url('^merged-invoice/(\d+)$', 'manager.views.invoice.merged_invoice', name='merged_invoice_info'),
    url('^merged-invoice/update/(\d+)$', 'manager.views.invoice.update_merged_invoice', name='update_merged_invoice'),
    url('^merged-invoice/all$', 'manager.views.invoice.merged_invoice_list', name='merged_invoice_list'),
    url('^merged-invoice/delete/(\d+)$', 'manager.views.invoice.delete_merged_invoice', name='delete_merged_invoice'),

    url('^past-invoices$', 'manager.views.invoice.past_invoices', name='past_invoices'),

    url('^attendee/table/all$', 'manager.views.attendee.table_list', name='table_list'),
    url('^attendee/table/detail$', 'manager.views.attendee.table_attendee_detail', name='table_attendee_detail'),
    url('^invoice/table/list/all$', 'manager.views.invoice.table_list', name='table_invoices'),
    url('^invoice/table/detail/$', 'manager.views.invoice.table_invoice_detail', name='table_invoice_detail'),


    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

manager/models/attendee.py
from django.db import models
import datetime

from manager.models.invoice import Invoice



class Attendee(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    table_assignment = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    bid_number = models.IntegerField(max_length=3)
    year = models.IntegerField(default=lambda: datetime.datetime.now().year, editable=False)



    class Meta:
        verbose_name_plural = "attendees"
        app_label = 'manager'

    def __unicode__(self):
        return self.first_name + " " + self.last_name


    def create_invoice(self):
        try:
            invoice = Invoice.objects.get(attendee=self)
            return invoice
        except Invoice.DoesNotExist:
            invoice = Invoice.objects.create(total_amount=0, attendee=self)
            invoice.save()
            return invoice

    @property
    def name(self):
        return self.first_name + ' ' + self.last_name

manager/models/auction_item.py
from decimal import Decimal
from django.db import models
import datetime




class AuctionItem(models.Model):
    description = models.CharField(max_length=50, blank=True)
    date_received = models.DateField(default=lambda: datetime.datetime.now(), blank=True, null=True)
    invoice = models.ForeignKey('Invoice', related_name='items', default=None, blank=True, null=True)
    retail_value = models.DecimalField(decimal_places=2, max_digits=30)
    selling_price = models.DecimalField(decimal_places=2, max_digits=30, default=Decimal('0.00'), blank=True, null=True)
    starting_value = models.DecimalField(decimal_places=2, max_digits=30)
    increment_amount = models.DecimalField(decimal_places=2, max_digits=30)
    winning_bid_number = models.IntegerField(default=None, blank=True, null=True)
    year = models.IntegerField(default=lambda: datetime.datetime.now().year, editable=False)
    item_number = models.IntegerField(default=None)

    class Meta:
        verbose_name_plural = "auction items"
        app_label = 'manager'

    def __unicode__(self):
        return self.description

manager/models/models.py
from django.db import models

# Create your models here.

manager/views/attendee.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as django_login, logout as django_logout
from manager.models.attendee import Attendee
from manager.models.invoice import Invoice
from manager.models.auction_item import AuctionItem
from manager.forms import AttendeeForm, TableSelectForm, YearForm
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required



@login_required
def create(request):
    ''' creates a new attendee for the current year's auction.
    '''
    if request.POST:
        form = AttendeeForm(request.POST)
        if form.is_valid():
            attendee = form.save()
            attendee.create_invoice()
            messages.add_message(request, messages.SUCCESS, 'New Attendee Added. Invoice added and associated with attendee.')
            return redirect('attendee_list')
        else:
            if len(Attendee.objects.filter(year=lambda: datetime.datetime.now().year)) > 0:
                latest_attendee = Attendee.objects.latest('bid_number')
                bid_number = latest_attendee.bid_number + 1
            context = {'form': form,
                       'bid_number': bid_number,
                       'table_assignment': form.cleaned_data['table_assignment']}
            return render(request, 'attendee/add.html', context)
    else:
        form = AttendeeForm()
        # Check to see if there are attendees for this year's auction. If there are, set the default bid number
        # to one more than the highest bid number. If no attendees, set bid number to 1.
        if len(Attendee.objects.filter(year=lambda: datetime.datetime.now().year)) > 0:
            latest_attendee = Attendee.objects.latest('bid_number')
            bid_number = latest_attendee.bid_number + 1
        else:
            bid_number = 1
        context = {'form': form,
                   'bid_number': bid_number,
                   }
        return render(request, 'attendee/add.html', context)


@login_required
def update(request, id):
    ''' Updates an attendee record
    '''
    attendee = get_object_or_404(Attendee, id=id)
    # Get current list of bid numbers so we don't accidentally assign one that already exists.
    bid_list = [a.bid_number for a in Attendee.objects.filter(year=lambda: datetime.datetime.now().year).exclude(
        id=attendee.id)]
    if request.POST:
        form = AttendeeForm(request.POST, instance=attendee)
        if form.is_valid():
            if form.cleaned_data['bid_number'] in bid_list:
                messages.add_message(request, messages.WARNING, 'That bid number is already assigned to another guest')
                return redirect('attendee_info', id)
            else:
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Attendee Information updated for %s' % (attendee.first_name + " " + attendee.last_name))
                return redirect('attendee_list')
        else:
            return redirect('attendee_info', id)
    else:
        form = AttendeeForm(instance=attendee)
        context = {'attendee': attendee,
                   'form': form,
                   }

    return render(request, 'attendee/update.html', context)



@login_required
def info(request, id):
    ''' Gets info for an attendee
    '''
    attendee = Attendee.objects.get(id=id)
    return render(request, 'attendee/info.html', {'attendee': attendee})


@login_required
def list(request):
    ''' Get a list of all attendees for the current year's auction.
    '''
    attendees = Attendee.objects.filter(year=lambda: datetime.datetime.now().year)
    context = {'attendees': attendees,
               }
    return render(request, 'attendee/attendee_list.html', context)


@login_required
def delete(request, id):
    '''
    deletes an attendee
    '''
    attendee = Attendee.objects.get(id=id)
    attendee.delete()
    return redirect('attendee_list')


@login_required
def table_list(request):
    '''
    orders attendees by table
    '''
    attendees = Attendee.objects.all().order_by('table_assignment')
    context = {'attendees': attendees}
    return render(request, 'attendee/table_list.html', context)

@login_required
def table_attendee_detail(request):
    '''
    View to retrieve all attendees at a certain table
    '''
    choices = set([(a.table_assignment, a.table_assignment) for a in Attendee.objects.filter(year=datetime.datetime.now().year)])

    if request.POST:
        form = TableSelectForm(request.POST, CHOICES=choices)
        if form.is_valid():
            attendees = Attendee.objects.filter(table_assignment=form.cleaned_data['table_assignment'])
            context = {'attendees': attendees,
                       'form': form}
    else:
        form = TableSelectForm(CHOICES=choices)
        context = {'form': form}
    return render(request, 'attendee/table_detail_list.html', context)



@login_required
def past_attendees(request):
    ''' Get a list of all auction items for the a past year's auction.
    '''
    context = {}
    if request.POST:
        form = YearForm(request.POST)
        if form.is_valid():
            attendees = Attendee.objects.filter(year=form.cleaned_data['year'])
            context['attendees'] = attendees
            context['year'] = form.cleaned_data['year']
        else:
            context['errors'] = form.errors
            context['form'] = form
        return render(request, 'attendee/attendee_list.html', context)
    else:
        form = YearForm()
        context['form'] = form
    return render(request, 'attendee/attendee_list.html', context)

manager/views/auction_item.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from manager.models.invoice import Invoice
from manager.models.attendee import Attendee
from manager.models.auction_item import AuctionItem
from manager.forms import AuctionItemForm, ItemSearchForm, YearForm
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def create(request):
    ''' creates a new auction item for the current year's auction.
    '''
    if request.POST:
        form = AuctionItemForm(request.POST)
        if form.is_valid():
            exists = AuctionItem.objects.filter(item_number=form.cleaned_data['item_number'], year=lambda: datetime.datetime.now().year)
            if not exists:
                item = form.save()
                messages.add_message(request, messages.SUCCESS, 'Auction Item created')
                return redirect('item_list')
            else:
                messages.add_message(request, messages.WARNING, 'Item with that number exists.')
                return redirect('item_list')
        else:
            context = {'form': form}
            return render(request, 'auction_item/add.html', context)
    else:
        form = AuctionItemForm()
        context = {'form': form,
                   }
        return render(request, 'auction_item/add.html', context)


@login_required
def update(request, id):
    ''' Updates an auction item record
    '''
    item = get_object_or_404(AuctionItem, id=id)

    if request.POST:
        form = AuctionItemForm(request.POST, instance=item)
        if form.is_valid():
            item = AuctionItem.objects.get(id=id)
            if form.cleaned_data['item_number'] != item.item_number:
                try:
                    exists = AuctionItem.objects.get(item_number=form.cleaned_data['item_number'], year=lambda: datetime.datetime.now().year)
                    messages.add_message(request, messages.WARNING, 'Another item already has the number %i.' % form.cleaned_data['item_number'])
                except AuctionItem.DoesNotExist:
                    item.item_number = form.cleaned_data['item_number']
                    item.save()
                    messages.add_message(request, messages.SUCCESS, 'Item Number successfully updated.')
            elif form.cleaned_data['winning_bid_number']:
                try:
                    attendee = Attendee.objects.get(bid_number=form.cleaned_data['winning_bid_number'])
                except ObjectDoesNotExist:
                    messages.add_message(request, messages.WARNING, 'No attendee found with that bid number.')
                    return redirect('item_list')
                invoice = Invoice.objects.get(attendee=attendee)
                item.winning_bid_number = form.cleaned_data['winning_bid_number']
                invoice.items.add(item)
                messages.add_message(request, messages.SUCCESS, 'Winning bidder set for item %s.' % item.description)
                if form.cleaned_data['selling_price'] != item.selling_price:
                    item.selling_price = form.cleaned_data['selling_price']
                    messages.add_message(request, messages.SUCCESS, 'Selling price set.')
                item.save()
            else:
                form.save()
                messages.add_message(request, messages.WARNING, 'Item %s updated' % form.cleaned_data['description'])
        else:
            messages.add_message(request, messages.WARNING, 'Something went wrong in the validation of the form. Please try again and ensure all the information is correct')
        return redirect('item_list')
    else:
        form = AuctionItemForm(instance=item)
        context = {'auction_item': item,
                   'form': form,
                   }

    return render(request, 'auction_item/update.html', context)



@login_required
def detail(request, id):
    ''' Get item's info
    '''
    item = AuctionItem.objects.get(id=id)
    return render(request, 'auction_item/info.html', {'item': item})


@login_required
def item_search(request):
    """
    Search for Item by item number
    """
    context = {}
    if request.POST:
        form = ItemSearchForm(request.POST)
        if form.is_valid():
            try:
                item = AuctionItem.objects.get(item_number=form.cleaned_data['item_number'])
                context['item'] = item
                context['form'] = form
            except AuctionItem.DoesNotExist as e:
                context['error'] = e
        else:
            return render(request, 'quction_item/item_search.html', context)
    else:
        form = ItemSearchForm()
        context['form'] = form

    return render(request, 'auction_item/item_search.html', context)



@login_required
def unsold_item_list(request):
    ''' Get a list of all unsold auction items for the current year's auction.
    '''
    items = AuctionItem.objects.filter(year=lambda: datetime.datetime.now().year, winning_bid_number__isnull=True)
    context = {'auction_items': items,
               }
    return render(request, 'auction_item/item_list.html', context)


@login_required
def past_items(request):
    ''' Get a list of all auction items for the a past year's auction.
    '''
    context = {}
    if request.POST:
        form = YearForm(request.POST)
        if form.is_valid():
            items = AuctionItem.objects.filter(year=form.cleaned_data['year'])
            context['auction_items'] = items
            context['year'] = form.cleaned_data['year']
        else:
            context['errors'] = form.errors
            context['form'] = form
        return render(request, 'auction_item/item_list.html', context)
    else:
        form = YearForm()
        context['form'] = form
    return render(request, 'auction_item/item_list.html', context)


@login_required
def list(request):
    ''' Get a list of all auction items for the current year's auction.
    '''
    items = AuctionItem.objects.filter(year=lambda: datetime.datetime.now().year)
    context = {'auction_items': items,
               }
    return render(request, 'auction_item/item_list.html', context)


@login_required
def delete(request, id):
    item = AuctionItem.objects.get(id=id)
    item.delete()
    return redirect('item_list')

manager/templates/attendee/add.html
{% extends 'base.html' %}
{% block content %}

{% if form.errors %}
    {{ form.errors }}
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    First Name: {{ form.first_name }}<br/>
    Last Name: {{ form.last_name }}<br/>
    <label for="id_table_assignment">Table Assignment:</label><input id="id_table_assignment" name="table_assignment" value="{{ table_assignment }}"/><br/>
    Phone: {{ form.phone }}<br/>
    Email: {{ form.email }}<br/>
    <label for="id_bid_number">Bid Number:</label> {{ bid_number }}<input id="id_bid_number" name="bid_number" type="hidden" value="{{ bid_number }}"/><br/>
    <input type="submit" value="Save New Attendee" id="submit">
</form>




{% endblock %}

manager/templates/attendee/attendee_list.html
{% extends 'base.html' %}

{% block content %}

{% if form %}
<div class="centered-text">
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Get Attendees" id="submit">
    </form>
</div>
{% endif %}


{% if year %}
    <div class="centered-text">
        <h2>Attendees for {{ year }}</h2>
    </div>
{% endif %}



<table border="1px solid" class="centered_list">
    <tr>
        <th>Name</th>
        <th>Table Assignment</th>
        <th>Bid Number</th>
    </tr>
{% for attendee in attendees %}
    <tr>
        <td>
            <a href="{% url 'attendee_info' attendee.id %}">{{ attendee.first_name }} {{ attendee.last_name }}</a><br/>
        </td>
        <td>
            {{ attendee.table_assignment }}
        </td>
        <td>
            {{ attendee.bid_number }}
        </td>
        <td><div>
            <a href="{% url 'update_attendee' attendee.id %}"><button type="button" id="submit">Update</button></a>
            </div>
        </td>
        <td><div class="confirm">
            <a href="{% url 'delete_attendee' attendee.id %}"><button type="button" id="submit">Delete</button></a>
            </div>
        </td>
    </tr>
{% endfor %}
</table>

{% include 'partials/confirm-js.html' %}

{% endblock %}

manager/templates/attendee/info.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'update_attendee' attendee.id %}" method="get">
    {% csrf_token %}

    <table border="1px solid">
        <tr>
            <th>Record ID:</th>
            <td>{{ attendee.id }}</td>
        </tr>
        <tr>
            <th>First Name:</th>
            <td>{{ attendee.first_name }}</td>
        </tr>
        <tr>
            <th>Last Name:</th>
            <td>{{ attendee.last_name }}</td>
        </tr>
        <tr>
            <th>Table Assignment:</th>
            <td>{{ attendee.table_assignment }}</td>
        </tr>
        <tr>
            <th>Bid Number:</th>
            <td>{{ attendee.bid_number }}</td>
        </tr>
        <tr>
            <th>Phone:</th>
            <td>{{ attendee.phone }}</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>{{ attendee.email }}</td>
        </tr>
        <tr>
            <th>Invoice</th>
            <td>
                {% if attendee.invoice %}
                <a href="{% url 'invoice_details' attendee.invoice.id %}">{{ attendee.invoice }}</a>
                {% else %}
                <a href="{% url 'add_invoice' %}">Create Invoice</a>
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Invoice Items</th>
            <td>
                {% if attendee.invoice.items.all %}
                {% for item in attendee.invoice.items.all %}
                {{ item }}<br/>
                {% endfor %}
                {% endif %}
            </td>
        </tr>

    </table>

    <input type="hidden" value="{{ attendee }}" name="attendee"/>
    <input type="submit" value="Update Attendee" name="update_attendee" id="submit" />
</form>




{% if error %}

No Attendee information found for attendee with ID {{ id }}

{% endif %}


{% endblock %}

manager/templates/attendee/table_detail_list.html
{% extends 'base.html' %}

{% block content %}


{% if form %}
<form action="" method="post">
{% csrf_token %}
    {{ form.table_assignment }}
<input type="submit" value="Search for this table" id="submit"/>
</form>
{% endif %}


{% if attendees %}
<table border="1px solid" class="centered_list">
    <tr>
        <th>Record Id</th>
        <th>Name</th>
        <th>Table Assignment</th>
        <th>Bid Number</th>
    </tr>
{% for attendee in attendees %}
    <tr>
        <td>{{ attendee.id }}</td>
        <td>
            <a href="{% url 'attendee_info' attendee.id %}">{{ attendee.first_name }} {{ attendee.last_name }}</a><br/>
        </td>
        <td>
            {{ attendee.table_assignment }}
        </td>
        <td>
            {{ attendee.bid_number }}
        </td>
        <td>
            <form method="post" action="{% url 'add_attendee' %}">
                {% csrf_token %}
                <input type="hidden" name="table_assignment" value="{{ attendee.table_assignment }}"/>
                <input type="submit" value="Add attendee to table" id="submit" />
            </form>
        </td>
    </tr>
{% endfor %}
</table>
{% endif %}


{% endblock %}

manager/templates/attendee/table_list.html
{% extends 'base.html' %}

{% block content %}
<table border="1px solid" class="centered_list">
    <tr>
        <th>Record Id</th>
        <th>Name</th>
        <th>Table Assignment</th>
        <th>Bid Number</th>
    </tr>
{% for attendee in attendees %}
    <tr>
        <td>{{ attendee.id }}</td>
        <td>
            <a href="{% url 'attendee_info' attendee.id %}">{{ attendee.first_name }} {{ attendee.last_name }}</a><br/>
        </td>
        <td>
            {{ attendee.table_assignment }}
        </td>
        <td>
            {{ attendee.bid_number }}
        </td>
        <td>
            <form method="post" action="{% url 'add_attendee' %}">
                {% csrf_token %}
                <input type="hidden" name="table_assignment" value="{{ attendee.table_assignment }}"/>
                <input type="submit" value="Add attendee to table"/>
            </form>
        </td>
    </tr>
{% endfor %}
</table>
{% endblock %}

manager/templates/attendee/update.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}

    <table border="1px solid">
        <tr>
            <th>Record ID:</th>
            <td>{{ attendee.id }}</td>
        </tr>
        <tr>
            <th>First Name:</th>
            <td>{{ form.first_name }}</td>
        </tr>
        <tr>
            <th>Last Name:</th>
            <td>{{ form.last_name }}</td>
        </tr>
        <tr>
            <th>Table Assignment:</th>
            <td>{{ form.table_assignment }}</td>
        </tr>
        <tr>
            <th>Bid Number:</th>
            <td>{{ form.bid_number }}</td>
        </tr>
        <tr>
            <th>Phone:</th>
            <td>{{ form.phone }}</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>{{ form.email }}</td>
        </tr>
    </table>

    <input type="hidden" value="{{ attendee }}" name="attendee"/>
    <input type="submit" id="submit" value="Update Attendee" name="update_attendee"/>
</form>




{% if error %}

No Attendee information found for attendee with ID {{ id }}

{% endif %}


{% endblock %}