auctionmanageronline/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'manager.views.home.home', name='home'),
    url(r'^login/$', 'manager.views.home.login', name='login'),
    url(r'^logout/$', 'manager.views.home.logout', name='logout'),


    url('^attendee/add/$', 'manager.views.attendee.create', name='add_attendee'),
    url('^attendee/(\d+)$', 'manager.views.attendee.info', name='attendee_info'),
    url('^attendee/update/(\d+)$', 'manager.views.attendee.update', name='update_attendee'),
    url('^attendee/all$', 'manager.views.attendee.list', name='attendee_list'),
    url('^attendee/delete/(\d+)$', 'manager.views.attendee.delete', name='delete_attendee'),
    url('^past-attendees$', 'manager.views.attendee.past_attendees', name='past_attendees'),

    url('^item/add/$', 'manager.views.auction_item.create', name='add_item'),
    url('^item/(\d+)$', 'manager.views.auction_item.detail', name='item_detail'),
    url('^item/update/(\d+)$', 'manager.views.auction_item.update', name='update_item'),
    url('^item/all$', 'manager.views.auction_item.list', name='item_list'),
    url('^item/delete/(\d+)$', 'manager.views.auction_item.delete', name='delete_item'),
    url('^item/search/$', 'manager.views.auction_item.item_search', name='item_search'),
    url('^item/unsold/all$', 'manager.views.auction_item.unsold_item_list', name='unsold_items'),
    url('^past-items$', 'manager.views.auction_item.past_items', name='past_items'),

    url('^invoice/add/$', 'manager.views.invoice.create', name='add_invoice'),
    url('^invoice/(\d+)$', 'manager.views.invoice.detail', name='invoice_details'),
    url('^invoice/bidder$', 'manager.views.invoice.bidder_invoice_search', name='bidder_invoice'),
    url('^invoice/update/(\d+)$', 'manager.views.invoice.update', name='update_invoice'),
    url('^invoice/all$', 'manager.views.invoice.list', name='invoice_list'),
    url('^invoice/delete/(\d+)$', 'manager.views.invoice.delete', name='delete_invoice'),
    url('^invoice/unpaid/$', 'manager.views.invoice.unpaid_invoices', name='unpaid_invoices'),

    url('^invoice/merge/$', 'manager.views.invoice.merge_invoices', name='merge_invoices'),
    url('^merged-invoice/(\d+)$', 'manager.views.invoice.merged_invoice', name='merged_invoice_info'),
    url('^merged-invoice/update/(\d+)$', 'manager.views.invoice.update_merged_invoice', name='update_merged_invoice'),
    url('^merged-invoice/all$', 'manager.views.invoice.merged_invoice_list', name='merged_invoice_list'),
    url('^merged-invoice/delete/(\d+)$', 'manager.views.invoice.delete_merged_invoice', name='delete_merged_invoice'),

    url('^past-invoices$', 'manager.views.invoice.past_invoices', name='past_invoices'),

    url('^attendee/table/all$', 'manager.views.attendee.table_list', name='table_list'),
    url('^attendee/table/detail$', 'manager.views.attendee.table_attendee_detail', name='table_attendee_detail'),
    url('^invoice/table/list/all$', 'manager.views.invoice.table_list', name='table_invoices'),
    url('^invoice/table/detail/$', 'manager.views.invoice.table_invoice_detail', name='table_invoice_detail'),


    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

manager/models/attendee.py
from django.db import models
import datetime

from manager.models.invoice import Invoice



class Attendee(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    table_assignment = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    bid_number = models.IntegerField(max_length=3)
    year = models.IntegerField(default=lambda: datetime.datetime.now().year, editable=False)



    class Meta:
        verbose_name_plural = "attendees"
        app_label = 'manager'

    def __unicode__(self):
        return self.first_name + " " + self.last_name


    def create_invoice(self):
        try:
            invoice = Invoice.objects.get(attendee=self)
            return invoice
        except Invoice.DoesNotExist:
            invoice = Invoice.objects.create(total_amount=0, attendee=self)
            invoice.save()
            return invoice

    @property
    def name(self):
        return self.first_name + ' ' + self.last_name

manager/models/auction_item.py
from decimal import Decimal
from django.db import models
import datetime




class AuctionItem(models.Model):
    description = models.CharField(max_length=50, blank=True)
    date_received = models.DateField(default=lambda: datetime.datetime.now(), blank=True, null=True)
    invoice = models.ForeignKey('Invoice', related_name='items', default=None, blank=True, null=True)
    retail_value = models.DecimalField(decimal_places=2, max_digits=30)
    selling_price = models.DecimalField(decimal_places=2, max_digits=30, default=Decimal('0.00'), blank=True, null=True)
    starting_value = models.DecimalField(decimal_places=2, max_digits=30)
    increment_amount = models.DecimalField(decimal_places=2, max_digits=30)
    winning_bid_number = models.IntegerField(default=None, blank=True, null=True)
    year = models.IntegerField(default=lambda: datetime.datetime.now().year, editable=False)
    item_number = models.IntegerField(default=None)

    class Meta:
        verbose_name_plural = "auction items"
        app_label = 'manager'

    def __unicode__(self):
        return self.description

manager/models/models.py
from django.db import models

# Create your models here.

manager/views/attendee.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as django_login, logout as django_logout
from manager.models.attendee import Attendee
from manager.models.invoice import Invoice
from manager.models.auction_item import AuctionItem
from manager.forms import AttendeeForm, TableSelectForm, YearForm
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required



@login_required
def create(request):
    ''' creates a new attendee for the current year's auction.
    '''
    if request.POST:
        form = AttendeeForm(request.POST)
        if form.is_valid():
            attendee = form.save()
            attendee.create_invoice()
            messages.add_message(request, messages.SUCCESS, 'New Attendee Added. Invoice added and associated with attendee.')
            return redirect('attendee_list')
        else:
            if len(Attendee.objects.filter(year=lambda: datetime.datetime.now().year)) > 0:
                latest_attendee = Attendee.objects.latest('bid_number')
                bid_number = latest_attendee.bid_number + 1
            context = {'form': form,
                       'bid_number': bid_number,
                       'table_assignment': form.cleaned_data['table_assignment']}
            return render(request, 'attendee/add.html', context)
    else:
        form = AttendeeForm()
        # Check to see if there are attendees for this year's auction. If there are, set the default bid number
        # to one more than the highest bid number. If no attendees, set bid number to 1.
        if len(Attendee.objects.filter(year=lambda: datetime.datetime.now().year)) > 0:
            latest_attendee = Attendee.objects.latest('bid_number')
            bid_number = latest_attendee.bid_number + 1
        else:
            bid_number = 1
        context = {'form': form,
                   'bid_number': bid_number,
                   }
        return render(request, 'attendee/add.html', context)


@login_required
def update(request, id):
    ''' Updates an attendee record
    '''
    attendee = get_object_or_404(Attendee, id=id)
    # Get current list of bid numbers so we don't accidentally assign one that already exists.
    bid_list = [a.bid_number for a in Attendee.objects.filter(year=lambda: datetime.datetime.now().year).exclude(
        id=attendee.id)]
    if request.POST:
        form = AttendeeForm(request.POST, instance=attendee)
        if form.is_valid():
            if form.cleaned_data['bid_number'] in bid_list:
                messages.add_message(request, messages.WARNING, 'That bid number is already assigned to another guest')
                return redirect('attendee_info', id)
            else:
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Attendee Information updated for %s' % (attendee.first_name + " " + attendee.last_name))
                return redirect('attendee_list')
        else:
            return redirect('attendee_info', id)
    else:
        form = AttendeeForm(instance=attendee)
        context = {'attendee': attendee,
                   'form': form,
                   }

    return render(request, 'attendee/update.html', context)



@login_required
def info(request, id):
    ''' Gets info for an attendee
    '''
    attendee = Attendee.objects.get(id=id)
    return render(request, 'attendee/info.html', {'attendee': attendee})


@login_required
def list(request):
    ''' Get a list of all attendees for the current year's auction.
    '''
    attendees = Attendee.objects.filter(year=lambda: datetime.datetime.now().year)
    context = {'attendees': attendees,
               }
    return render(request, 'attendee/attendee_list.html', context)


@login_required
def delete(request, id):
    '''
    deletes an attendee
    '''
    attendee = Attendee.objects.get(id=id)
    attendee.delete()
    return redirect('attendee_list')


@login_required
def table_list(request):
    '''
    orders attendees by table
    '''
    attendees = Attendee.objects.all().order_by('table_assignment')
    context = {'attendees': attendees}
    return render(request, 'attendee/table_list.html', context)

@login_required
def table_attendee_detail(request):
    '''
    View to retrieve all attendees at a certain table
    '''
    choices = set([(a.table_assignment, a.table_assignment) for a in Attendee.objects.filter(year=datetime.datetime.now().year)])

    if request.POST:
        form = TableSelectForm(request.POST, CHOICES=choices)
        if form.is_valid():
            attendees = Attendee.objects.filter(table_assignment=form.cleaned_data['table_assignment'])
            context = {'attendees': attendees,
                       'form': form}
    else:
        form = TableSelectForm(CHOICES=choices)
        context = {'form': form}
    return render(request, 'attendee/table_detail_list.html', context)



@login_required
def past_attendees(request):
    ''' Get a list of all auction items for the a past year's auction.
    '''
    context = {}
    if request.POST:
        form = YearForm(request.POST)
        if form.is_valid():
            attendees = Attendee.objects.filter(year=form.cleaned_data['year'])
            context['attendees'] = attendees
            context['year'] = form.cleaned_data['year']
        else:
            context['errors'] = form.errors
            context['form'] = form
        return render(request, 'attendee/attendee_list.html', context)
    else:
        form = YearForm()
        context['form'] = form
    return render(request, 'attendee/attendee_list.html', context)

manager/views/auction_item.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from manager.models.invoice import Invoice
from manager.models.attendee import Attendee
from manager.models.auction_item import AuctionItem
from manager.forms import AuctionItemForm, ItemSearchForm, YearForm
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def create(request):
    ''' creates a new auction item for the current year's auction.
    '''
    if request.POST:
        form = AuctionItemForm(request.POST)
        if form.is_valid():
            exists = AuctionItem.objects.filter(item_number=form.cleaned_data['item_number'], year=lambda: datetime.datetime.now().year)
            if not exists:
                item = form.save()
                messages.add_message(request, messages.SUCCESS, 'Auction Item created')
                return redirect('item_list')
            else:
                messages.add_message(request, messages.WARNING, 'Item with that number exists.')
                return redirect('item_list')
        else:
            context = {'form': form}
            return render(request, 'auction_item/add.html', context)
    else:
        form = AuctionItemForm()
        context = {'form': form,
                   }
        return render(request, 'auction_item/add.html', context)


@login_required
def update(request, id):
    ''' Updates an auction item record
    '''
    item = get_object_or_404(AuctionItem, id=id)

    if request.POST:
        form = AuctionItemForm(request.POST, instance=item)
        if form.is_valid():
            item = AuctionItem.objects.get(id=id)
            if form.cleaned_data['item_number'] != item.item_number:
                try:
                    exists = AuctionItem.objects.get(item_number=form.cleaned_data['item_number'], year=lambda: datetime.datetime.now().year)
                    messages.add_message(request, messages.WARNING, 'Another item already has the number %i.' % form.cleaned_data['item_number'])
                except AuctionItem.DoesNotExist:
                    item.item_number = form.cleaned_data['item_number']
                    item.save()
                    messages.add_message(request, messages.SUCCESS, 'Item Number successfully updated.')
            elif form.cleaned_data['winning_bid_number']:
                try:
                    attendee = Attendee.objects.get(bid_number=form.cleaned_data['winning_bid_number'])
                except ObjectDoesNotExist:
                    messages.add_message(request, messages.WARNING, 'No attendee found with that bid number.')
                    return redirect('item_list')
                invoice = Invoice.objects.get(attendee=attendee)
                item.winning_bid_number = form.cleaned_data['winning_bid_number']
                invoice.items.add(item)
                messages.add_message(request, messages.SUCCESS, 'Winning bidder set for item %s.' % item.description)
                if form.cleaned_data['selling_price'] != item.selling_price:
                    item.selling_price = form.cleaned_data['selling_price']
                    messages.add_message(request, messages.SUCCESS, 'Selling price set.')
                item.save()
            else:
                form.save()
                messages.add_message(request, messages.WARNING, 'Item %s updated' % form.cleaned_data['description'])
        else:
            messages.add_message(request, messages.WARNING, 'Something went wrong in the validation of the form. Please try again and ensure all the information is correct')
        return redirect('item_list')
    else:
        form = AuctionItemForm(instance=item)
        context = {'auction_item': item,
                   'form': form,
                   }

    return render(request, 'auction_item/update.html', context)



@login_required
def detail(request, id):
    ''' Get item's info
    '''
    item = AuctionItem.objects.get(id=id)
    return render(request, 'auction_item/info.html', {'item': item})


@login_required
def item_search(request):
    """
    Search for Item by item number
    """
    context = {}
    if request.POST:
        form = ItemSearchForm(request.POST)
        if form.is_valid():
            try:
                item = AuctionItem.objects.get(item_number=form.cleaned_data['item_number'])
                context['item'] = item
                context['form'] = form
            except AuctionItem.DoesNotExist as e:
                context['error'] = e
        else:
            return render(request, 'quction_item/item_search.html', context)
    else:
        form = ItemSearchForm()
        context['form'] = form

    return render(request, 'auction_item/item_search.html', context)



@login_required
def unsold_item_list(request):
    ''' Get a list of all unsold auction items for the current year's auction.
    '''
    items = AuctionItem.objects.filter(year=lambda: datetime.datetime.now().year, winning_bid_number__isnull=True)
    context = {'auction_items': items,
               }
    return render(request, 'auction_item/item_list.html', context)


@login_required
def past_items(request):
    ''' Get a list of all auction items for the a past year's auction.
    '''
    context = {}
    if request.POST:
        form = YearForm(request.POST)
        if form.is_valid():
            items = AuctionItem.objects.filter(year=form.cleaned_data['year'])
            context['auction_items'] = items
            context['year'] = form.cleaned_data['year']
        else:
            context['errors'] = form.errors
            context['form'] = form
        return render(request, 'auction_item/item_list.html', context)
    else:
        form = YearForm()
        context['form'] = form
    return render(request, 'auction_item/item_list.html', context)


@login_required
def list(request):
    ''' Get a list of all auction items for the current year's auction.
    '''
    items = AuctionItem.objects.filter(year=lambda: datetime.datetime.now().year)
    context = {'auction_items': items,
               }
    return render(request, 'auction_item/item_list.html', context)


@login_required
def delete(request, id):
    item = AuctionItem.objects.get(id=id)
    item.delete()
    return redirect('item_list')

manager/templates/auction_item/add.html
{% extends 'base.html' %}


{% block content %}

{% if form.errors %}
{{ form.errors }}
{% endif %}


<form action="" method="post">
    {% csrf_token %}
    Item Number: {{ form.item_number }}<br/>
    Description: {{ form.description }}<br/>
    ** Make sure your date is in the format of YYYY-MM-DD **<br/>
    Date Received: {{ form.date_received }}<br/>
    Starting Value: {{ form.starting_value }}<br/>
    Increment Amount: {{ form.increment_amount }}<br/>
    Retail Value: {{ form.retail_value }}<br/>
    <input id="id_selling_price" name="selling_price" step="0.01" type="hidden" value="0.00" /><br/>
    <input type="submit" id="submit" value="Save New Auction Item">
</form>

{% endblock %}

manager/templates/auction_item/info.html
{% extends 'base.html' %}


{% block content %}

{% if form.errors %}
{{ form.errors }}
{{ form.non_field_errors }}
{% endif %}

<table border="1px solid">
    <tr>
        <td>
            Item Number
        </td>
        <td>
            {{ item.item_number }}
        </td>
    </tr>
    <tr>
        <td>
            Description
        </td>
        <td>
            {{ item.description }}
        </td>
    </tr>
    <tr>
        <td>
            Winning Bidder
        </td>
        <td>
            {% if item.winning_bid_number %}{{ item.winning_bid_number }}{% else %}No Info{% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Invoice
        </td>
        <td>
            {% if item.invoice %}{{ item.invoice }}{% else %}No Invoice Associated Yet{% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Retail Value
        </td>
        <td>
            {% if item.retail_value %}${{ item.retail_value }}{% else %}No Info{% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Selling Price
        </td>
        <td>
            {% if item.selling_price %}${{ item.selling_price }}{% else %}No Info{% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Starting Value
        </td>
        <td>
            {% if item.starting_value %}${{ item.starting_value }}{% else %}No Info{% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Increment Amount
        </td>
        <td>
            {% if item.increment_amount %}${{ item.increment_amount }}{% else %}No Info{% endif %}
        </td>
    </tr>

</table>
<br/>
<a href="{% url 'update_item' item.id%}"><button id="submit" type="button">Update Item</button></a>


{% endblock %}

manager/templates/auction_item/item_list.html
{% extends 'base.html' %}


{% block content %}

{% if form %}
<div class="centered-text">
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Get Items" id="submit">
    </form>
</div>
{% endif %}

{% if year %}
    <div class="centered-text">
        <h2>Items for {{ year }}</h2>
    </div>
{% endif %}


<table border="1px solid" class="centered_list">
    <tr>
        <th>Item Number</th>
        <th>Item Description</th>
        <th>Winnning Bid Number</th>
        <th>Invoice</th>
        <th>Retail Price</th>
        <th>Selling Price</th>
        <th>Starting Value</th>
        <th>Increment Amount</th>
    </tr>

    {% for item in auction_items %}

    <tr>
        <td><a href="{% url 'item_detail' item.id %}">{{ item.item_number }}</a></td>
        <td>{% if item.description %}{{ item.description }}{% else %}No Description{% endif %}</td>
        <td>{{ item.winning_bid_number }}</td>
        <td>{% if item.invoice %}<a href="{% url 'invoice_details' item.invoice.id %}">{{ item.invoice }}</a>{% else %}{{ item.invoice }}{% endif %}</td>
        <td>{% if item.retail_value %}${{ item.retail_value }}{% else %}No Info{% endif %}</td>
        <td>{% if item.selling_price %}${{ item.selling_price }}{% else %}No Info{% endif %}</td>
        <td>{% if item.starting_value %}${{ item.starting_value }}{% else %}No Info{% endif %}</td>
        <td>{% if item.increment_amount %}${{ item.increment_amount }}{% else %}No Info{% endif %}</td>
        <td><a href="{% url 'update_item' item.id %}"><button type="button" id="submit" >Update</button></a></td>
        <td><div class="confirm"><a href="{% url 'delete_item' item.id %}"><button type="button" id="submit" >Delete</button></a></div></td>
    </tr>
{% endfor %}


</table>

{% include 'partials/confirm-js.html' %}
{% endblock %}

manager/templates/auction_item/item_search.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
    {{ error }}
{% endif %}

{% if form %}
<form action="" method="post">
    {% csrf_token %}
    Item Number: {{ form.item_number }}<br/>
    <input type="submit" value="Search for item" id="submit" />
</form>
{% endif %}

{% if item %}
    <a href="{% url 'item_detail' item.id %}">{{ item.item_number }} - {{ item.description }}</a>
{% endif %}









{% endblock %}

manager/templates/auction_item/update.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}

    <table border="1px solid">
        <tr>
            <th>Item Number:</th>
            <td>{{ form.item_number }}</td>
        </tr>
        <tr>
            <th>Description:</th>
            <td>{{ form.description }}</td>
        </tr>
        <tr>
            <th>Date Received:</th>
            <td>{{ form.date_received }}</td>
        </tr>
        <tr>
            <th>Retail Value:</th>
            <td>{{ form.retail_value }}</td>
        </tr>
        <tr>
            <th>Selling Price:</th>
            <td>{{ form.selling_price }}</td>
        </tr>
        <tr>
            <th>Starting Value:</th>
            <td>{{ form.starting_value }}</td>
        </tr>
        <tr>
            <th>Increment Amount:</th>
            <td>{{ form.increment_amount }}</td>
        </tr>
        <tr>
            <th>Winning Bid Number:</th>
            <td>{{ form.winning_bid_number }}</td>
        </tr>
        {% comment %}
        <tr>
            <th>Invoice:</th>
            <td>{{ form.invoice }}</td>
        </tr>
        {% endcomment %}
    </table>

    <input type="hidden" value="{{ attendee }}" name="attendee"/>
    <input type="submit" id="submit" value="Update Auction Item" name="update_item"/>
</form>




{% if error %}

No Attendee information found for attendee with ID {{ id }}

{% endif %}


{% endblock %}